/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SendGiftRouteImport } from './routes/send-gift'
import { Route as TopicsRouteImport } from './routes/topics'
import { Route as BookNumberRouteImport } from './routes/book.$number'
import { Route as ChapterIdRouteImport } from './routes/chapter.$id'
import { Route as HadithNumberRouteImport } from './routes/hadith.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SendGiftRoute = SendGiftRouteImport.update({
  id: '/send-gift',
  path: '/send-gift',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsRoute = TopicsRouteImport.update({
  id: '/topics',
  path: '/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const BookNumberRoute = BookNumberRouteImport.update({
  id: '/book/$number',
  path: '/book/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const ChapterIdRoute = ChapterIdRouteImport.update({
  id: '/chapter/$id',
  path: '/chapter/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithNumberRoute = HadithNumberRouteImport.update({
  id: '/hadith/$number',
  path: '/hadith/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/projects': typeof ProjectsRoute
  '/send-gift': typeof SendGiftRoute
  '/topics': typeof TopicsRoute
  '/book/$number': typeof BookNumberRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/hadith/$number': typeof HadithNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/projects': typeof ProjectsRoute
  '/send-gift': typeof SendGiftRoute
  '/topics': typeof TopicsRoute
  '/book/$number': typeof BookNumberRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/hadith/$number': typeof HadithNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/projects': typeof ProjectsRoute
  '/send-gift': typeof SendGiftRoute
  '/topics': typeof TopicsRoute
  '/book/$number': typeof BookNumberRoute
  '/chapter/$id': typeof ChapterIdRoute
  '/hadith/$number': typeof HadithNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/downloads'
    | '/projects'
    | '/send-gift'
    | '/topics'
    | '/book/$number'
    | '/chapter/$id'
    | '/hadith/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/downloads'
    | '/projects'
    | '/send-gift'
    | '/topics'
    | '/book/$number'
    | '/chapter/$id'
    | '/hadith/$number'
  id:
    | '__root__'
    | '/'
    | '/announcements'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/downloads'
    | '/projects'
    | '/send-gift'
    | '/topics'
    | '/book/$number'
    | '/chapter/$id'
    | '/hadith/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  ProjectsRoute: typeof ProjectsRoute
  SendGiftRoute: typeof SendGiftRoute
  TopicsRoute: typeof TopicsRoute
  BookNumberRoute: typeof BookNumberRoute
  ChapterIdRoute: typeof ChapterIdRoute
  HadithNumberRoute: typeof HadithNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-gift': {
      id: '/send-gift'
      path: '/send-gift'
      fullPath: '/send-gift'
      preLoaderRoute: typeof SendGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics': {
      id: '/topics'
      path: '/topics'
      fullPath: '/topics'
      preLoaderRoute: typeof TopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$number': {
      id: '/book/$number'
      path: '/book/$number'
      fullPath: '/book/$number'
      preLoaderRoute: typeof BookNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapter/$id': {
      id: '/chapter/$id'
      path: '/chapter/$id'
      fullPath: '/chapter/$id'
      preLoaderRoute: typeof ChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/$number': {
      id: '/hadith/$number'
      path: '/hadith/$number'
      fullPath: '/hadith/$number'
      preLoaderRoute: typeof HadithNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  ProjectsRoute: ProjectsRoute,
  SendGiftRoute: SendGiftRoute,
  TopicsRoute: TopicsRoute,
  BookNumberRoute: BookNumberRoute,
  ChapterIdRoute: ChapterIdRoute,
  HadithNumberRoute: HadithNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
