/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SendGiftRouteImport } from './routes/send-gift'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BookNumberRouteImport } from './routes/book.$number'
import { Route as HadithNumberRouteImport } from './routes/hadith.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SendGiftRoute = SendGiftRouteImport.update({
  id: '/send-gift',
  path: '/send-gift',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BookNumberRoute = BookNumberRouteImport.update({
  id: '/book/$number',
  path: '/book/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithNumberRoute = HadithNumberRouteImport.update({
  id: '/hadith/$number',
  path: '/hadith/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/send-gift': typeof SendGiftRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book/$number': typeof BookNumberRoute
  '/hadith/$number': typeof HadithNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/send-gift': typeof SendGiftRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/book/$number': typeof BookNumberRoute
  '/hadith/$number': typeof HadithNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/bookmarks': typeof BookmarksRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/send-gift': typeof SendGiftRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/book/$number': typeof BookNumberRoute
  '/hadith/$number': typeof HadithNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/announcements'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/projects'
    | '/send-gift'
    | '/admin'
    | '/book/$number'
    | '/hadith/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/announcements'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/projects'
    | '/send-gift'
    | '/admin'
    | '/book/$number'
    | '/hadith/$number'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/announcements'
    | '/auth'
    | '/bookmarks'
    | '/contact'
    | '/projects'
    | '/send-gift'
    | '/_authenticated/admin'
    | '/book/$number'
    | '/hadith/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  BookmarksRoute: typeof BookmarksRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  SendGiftRoute: typeof SendGiftRoute
  BookNumberRoute: typeof BookNumberRoute
  HadithNumberRoute: typeof HadithNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send-gift': {
      id: '/send-gift'
      path: '/send-gift'
      fullPath: '/send-gift'
      preLoaderRoute: typeof SendGiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/book/$number': {
      id: '/book/$number'
      path: '/book/$number'
      fullPath: '/book/$number'
      preLoaderRoute: typeof BookNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith/$number': {
      id: '/hadith/$number'
      path: '/hadith/$number'
      fullPath: '/hadith/$number'
      preLoaderRoute: typeof HadithNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  BookmarksRoute: BookmarksRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  SendGiftRoute: SendGiftRoute,
  BookNumberRoute: BookNumberRoute,
  HadithNumberRoute: HadithNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
